-- ELIMINAR TODO --

USE Tomatazo;

DROP TABLE IF EXISTS Comentario;
DROP TABLE IF EXISTS Publicacion_Tag;
DROP TABLE IF EXISTS Tag;
DROP TABLE IF EXISTS Reaccion;
DROP TABLE IF EXISTS TipoReaccion;
DROP TABLE IF EXISTS Publicacion;
DROP TABLE IF EXISTS RelacionFollow;
DROP TABLE IF EXISTS Usuario;
DROP TABLE IF EXISTS Persona;
DROP TABLE IF EXISTS Empresa;
DROP TABLE IF EXISTS TipoUsuario;
